---
language: python
services: docker

env:
  global:
    - ROLE_NAME: firewall
  matrix:
    - MOLECULE_DISTRO: debian10
    # - MOLECULE_DISTRO: ubuntu1804
    # - MOLECULE_DISTRO: debian9


install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test

# yamllint disable rule:line-length
notifications:
  slack:
    secure: HJPvDJMHwKN8VUr00jr5xcbdjPILJSD8qRe84MYiv2yBrizYpXt1qMfTib8cYW0LvsB1Oq/CqaQ4DKJsNqnjRwMUWd+fAehBuGUzOeOa/gfcTnWSZscq0aVEcvb8p7rUAXWvVT1hwPE0k+wIgRhlDqwwBhTqZ+M8JkjepcXG+zY8/lMZFox7BmeD6kcFBpgkLHya/BnPtEje/aTQBnxhpNvddR4o0+LWmoL81OP23s2PJS7BYiLK5HLG20/91ThhjrCWX9KJGu1kkgwfX4IUWP/AaRKqOUW7UvsCskg/8hU/+x+kBFi3iYhIKgR08NBLBp/iEOQ94QjB2Gyjz2smqeAqlnkCPCr9AVXVkfiogQVWB7ATidC5EBkQ8LFvpTkHSpbYWMKjNqw9e4g7lVsanR9WFbC+6XvfF1tH2qNLy1mb6oIHJbZdrgD5558kxpDKFH1mFIs9oVuPAYjOAHy982dW40oh8bX0ualkRVs7G4vhbDVqLjEaY5b4PG2NBJScblokILLDoD9yMmXILyXOUMf/0J3Jroak7A+9i3jzyWIE2gmyFcJfSFJP9h7t+T+vNnDK4qeNtoq3nYZ/lh8nIZUu9qu+bXFklHJhWBc6PMZL8JszkUJcJxw8HDBvOUBD4WGyxGqVjb6w9Bfq5iPiOZv4ii1N3ztUUAJpFJhnhcE=
# yamllint enable rule:line-length
