---
# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  command: "{{ apache_daemon }} -v"
  changed_when: false
  check_mode: false
  register: _apache_version
  become: true

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- name: get apache vars
  include_vars: apache-22.yml
  when: "apache_version.split('.')[1] == '2'"

- name: get apache vars
  include_vars: apache-24.yml
  when: "apache_version.split('.')[1] == '4'"
