---

- name: Apache | change port configuration
  template:
    src: apache_ports.conf.j2
    dest: {{ apache_server_root }}/ports.conf

- name: Apache | change ServerName configuration
  template:
    src: apache_fqdn.conf.j2
    dest: "{{ apache_conf_available }}/fqdn.conf"

# note we could use a2enconf
- name: Apache | Link in configuration files
  file:
    src: "{{ apache_conf_available }}/{{ item }}"
    dest: "{{ apache_conf_enabled }}/{{ item }}"
    state: link
  with_items:
    - "fqdn.conf"
  when: apache_conf_enable_on


- name: Apache | Enable Apache mods.
  apache2_module: state=present name={{ item }}
  with_items: apache_enable_mods
  notify: restart apache

- name: Apache | Disable Apache Mods
  apache2_module: state=absent name={{ item }}
  with_items: apache_disable_mods
  notify: restart apache
  tags:
    - apache
    - security

- name: Apache  | Configure Apache EnvVars (Debian).
  lineinfile:
    dest: "{{ apache_server_root }}/envvars"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: apache_env_vars

  notify: restart apache

- name: Apache | Configure Apache (Debian)
  lineinfile:
    dest: "{{ apache_server_root }}/{{ apache_conf_main }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: apache_conf_vars
  notify: restart apache


- name: Apache | Configure Apache Logs (Debian)
  lineinfile:
    dest: "{{ apache_server_root }}/{{ apache_conf_main }}"
    regexp: "vhostproxy_combined$"
    insertafter: 'vhost_combined$'
    line: "{{ apache_vhc_format }}"
    state: "{{ apache_proxy_log }}"
    backup: true
  when: apache_vhc_format is defined

- name: Apache | Security | Server Tokens
  lineinfile:
    dest: "{{ apache_conf_available }}/{{ apache_security_conf }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: apache_security_vars

  notify: restart apache


