---

- name: Apache | change port configuration
  template: 
    src: apache_ports.conf.j2 
    dest: /etc/apache2/ports.conf
  
- name: Apache | change ServerName configuration
  template: 
    src: apache_fqdn.conf.j2 
    dest: "{{ apache_conf_available }}/fqdn.conf"

# note we could use a2enconf
- name: Apache | Link in configuration files
  file: 
    src: "{{ apache_conf_available }}/{{ item }}"
    dest: "{{ apache_conf_enabled }}/{{ item }}" 
    state: link
  with_items:
    - "fqdn.conf"


- name: Apache | Enable Apache mods.
  apache2_module: state=present name={{ item }}
  with_items: apache_mods_enabled
  notify: restart apache  

- name: Apache | Disable Apache Mods
  apache2_module: state=absent name={{ item }}
  with_items: apache_mods_disabled
  notify: restart apache
  tags: 
    - apache
    - security
  
- name: Apache  | Configure Apache (Debian).
  lineinfile: 
    dest: "{{ apache_server_root }}/envvars"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - {
    regexp: "^export APACHE_RUN_USER=",
    line: "export APACHE_RUN_USER={{ apache_run_user }}"
  }
  - {
    regexp: "^export APACHE_RUN_GROUP=",
    line: "export APACHE_RUN_GROUP={{ apache_run_group }}"
  }
  notify: restart apache

- name: Apache | Configure Apache (Debian)
  lineinfile: 
    dest: "{{ apache_server_root }}/{{ apache_conf_main }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - {
    regexp: "^Timeout",
    line: "Timeout {{ apache_timeout }}"
  }
  - {
    regexp: "^KeepAlive",
    line: "KeepAlive {{ apache_keepalive }}"
  }
  - {
    regexp: "^MaxKeepAliveRequests",
    line: "MaxKeepAliveRequests {{ apache_keepalive_max }}"
  }
  - {
    regexp: "^KeepAliveTimeout",
    line: "KeepAliveTimeout {{ apache_keepalive_to }}"
  }
  - {
    regexp: "^HostnameLookups",
    line: "HostnameLookups {{ apache_hostnamelookups }}"
  }
  - {
    regexp: "^LogLevel",
    line: "LogLevel {{ apache_loglevel }}"
  }
  notify: restart apache
  
- name: Apache | Security | Server Tokens
  lineinfile: 
    dest: "{{ apache_conf_available }}/{{ apache_security_conf }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - {
    regexp: "^ServerTokens",
    line: "ServerTokens {{ apache_server_tokens }}"
  }
  - {
    regexp: "^ServerSignature",
    line: "ServerSignature {{ apache_server_signature }}"
  }
  - {
    regexp: "^TraceEnable",
    line: "TraceEnable {{ apache_server_trace }}"
  }
  notify: restart apache


#- name: Apache | Update default host
#  template: src=apache_default_vhost.j2 dest="{{ apache_vhost_path }}/default"
#  tags: 
#   - apache
#  notify:
#    - restart apache

#- name: Apache | Setup default site
#  unarchive: >
#   src=default-site.tar
#   dest={{ apache_home_dir }}/
#   creates={{ apache_home_dir }}/default/index.html
#  tags: 
#    - apache
#    - defaultsite