---

# we may need to configure it before enabling
- name: Apache | Configure remoteip
  template:
    src: apache_remoteip.conf.j2
    dest: "{{ apache_mods_available }}/remoteip.conf"
    mode: 0644
    owner: root
    group: root
  when: apache_vhosts_version == '2.4' and apache_proxy == true
  notify: restart apache
  become: true

- name: Apache | Enable remoteip Apache mod.
  apache2_module: state=present name={{ item }}
  with_items:
    - remoteip
  notify: restart apache
  become: true
  when: apache_vhosts_version == '2.4' and apache_proxy == true

# - name:  Apache | Add remoteip header config
#   lineinfile:
#     dest: "{{ apache_server_root }}/{{ apache_conf_main }}"
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#     state: present
#   with_items:
#    - {
#     regexp: "^RemoteIPHeader ",
#     line: "RemoteIPHeader X-Forwarded-For"
#    }
#    - {
#     regexp: "^RemoteIPInternalProxy",
#     line: "RemoteIPInternalProxy {{ apache_proxy_ip }}"
#    }
  # when: apache_vhosts_version == '2.4' and apache_proxy == true
  # become: true
  # notify: restart apache


