---
# tasks file for apache-setup


# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ['always']

# Setup/install tasks.
# Base install of Apache

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Common setup
- import_tasks: setup-common.yml
  tags: [apache_setup]


# determine apache version
- import_tasks: apache-version.yml


# Configure Apache.

- import_tasks: configure-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: configure-Redhat-22.yml
  when: "ansible_os_family == 'RedHat' and apache_version.split('.')[1] == '2'"

- import_tasks: configure-Redhat-24.yml
  when: "ansible_os_family == 'RedHat' and apache_version.split('.')[1] == '4'"

- import_tasks: setup-ssl.yml
  static: false
  when: apache_tls_enabled

- import_tasks: configure-proxy.yml
  when: apache_proxy

- import_tasks: default-site.yml

- name: Create logrotate entry for apache logs
  template:
    src: logrotate-{{ apache_daemon }}.j2
    dest: "/etc/logrotate.d/{{ apache_daemon }}"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ apache_daemon }}"
    state: started
    enabled: yes
  become: true