---
# tasks file for apache-setup


# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


# Setup/install tasks.
# Base install of Apache

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Common setup
- include: setup-common.yml


# determine apache version
- include: apache-version.yml


# Configure Apache.

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'

- include: configure-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: default-site.yml

- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ apache_daemon }}"
    state: started
    enabled: yes