---
# tasks file for apache-setup


# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ['always']

# Setup/install tasks.
# Base install of Apache

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Common setup
- include: setup-common.yml
  tags: [apache_setup]


# determine apache version
- include: apache-version.yml


# Configure Apache.

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'

- include: configure-Redhat-22.yml
  when: "ansible_os_family == 'RedHat' and apache_version.split('.')[1] == '2'"

- include: configure-Redhat-24.yml
  when: "ansible_os_family == 'RedHat' and apache_version.split('.')[1] == '4'"

- include: setup-ssl.yml
  static: false
  when: apache_tls_enabled

- include: configure-proxy.yml
  when: apache_proxy

- include: default-site.yml

- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ apache_daemon }}"
    state: started
    enabled: yes
  become: true