---

- name: Apache | set up directories
  file: path={{ item.path }} state=directory recurse=yes
  with_items:
  - {
    path: "{{ apache_default_site }}",
  }
  tags: apache
  
  
- name: Apache | Create www-admin group for web
  group: 
    name: "{{ apache_admin_group }}"
    state: present
  tags: apache
  
- name: Apache | Add apache www-data user
  user: 
    name: "{{ apache_admin_user }}"
    groups: "{{ apache_run_group }}"
    append: yes
    group: "{{ apache_admin_group }}"
  sudo: true
  
# Note this module requires the package python-passlib  
- name: Apache | Create User password in Auth file
  htpasswd: 
     path: "{{ apache_auth_htpasswd_file }}"
     name: "{{ item.username }}"
     password: "{{ item.password }}"
     owner: root 
     group: "{{ apache_admin_user }}" 
     mode: 0644
  with_items:
    -  "{{ apache_auth_users }}"
    
# Todo write the authgroup file
# adding relevant users to groups
# see https://www.linode.com/docs/websites/authbased-access-control-with-apache    
    
    

# Apache user www-data is created on install of apache
#- name: Apache | Add apache www-data user
#  user: name=www-data
#        groups=www-admin
#        append=yes
#        group=www-data
#  sudo: true