---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  become: true

- name: Debian | Ensure Apache is installed.
  apt:
    name: "{{ apache_packages }}"
    state: present
  become: true

- name: Ensure MySQL packages are installed (client).
  apt:
    name: "{{ apache_mysql_packages }}"
    state: present
  when: apache_remote_db
  become: true
