---

- name: Define SSL directories (private).
  set_fact:
    ssl_private_dir: "{{ __ssl_private_dir }}"
  when: ssl_private_dir is not defined

- name: Define SSL directories (certs).
  set_fact:
    ssl_certs_dir: "{{ __ssl_certs_dir }}"
  when: ssl_certs_dir is not defined


- name: Setup default mod_ssl config
  template:
    src: apache_ssl.conf.j2
    dest: "{{ apache_mods_available }}/ssl.conf"
    owner: root
    group: root
    mode: 0644
  become: true
  tags: [ssl]
  when: ansible_os_family == 'Debian'

- name: Setup default mod_ssl config
  template:
    src: apache_ssl_redhat.conf.j2
    dest: "{{ apache_mods_available }}/ssl.conf"
    owner: root
    group: root
    mode: 0644
  become: true
  tags: [ssl]
  when: ansible_os_family == 'RedHat'

- name: Ensure ssl-certs group is present
  group:
    name: ssl-cert
    state: present
  sudo: yes
  tags: [ssl]

- name: Make sure Webserver run user is in ssl-cert group
  user:
    name: "{{ apache_run_user }}"
    groups: ssl-cert
    append: true
  sudo: yes
  tags: [ssl]

- name: Ensure the ssl certs dir exists
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
    recurse: yes
    owner: root
  with_items:
    - {
       path: '{{ ssl_certs_dir}}',
       mode: '0755'
       }
    - {
       path: '{{ ssl_private_dir }}',
       mode: '0700'
       }
  sudo: yes
  when: ssl_cert_upload
  tags: [ssl]


- name: Put certificate files in place
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    group: ssl-cert
  with_items:
    - "{{ ssl_certificate }}"
    - "{{ ssl_certificate_key }}"
    - "{{ ssl_certificate_chain|default([]) }}"
  when: ssl_cert_upload
  sudo: yes
  tags: [ssl]
  notify: restart apache


