---

- name: Apache | set up directories
  file: path={{ item.path }} state=directory recurse=yes
  with_items:
  - {
    path: "{{ apache_default_site }}",
  }
  tags: apache


- name: Apache | Create www-admin group for web
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ apache_admin_group }}"
    - "{{ apache_run_group }}"
  tags: apache

- name: Apache | Add apache www-admin user
  user:
    name: "{{ apache_admin_user }}"
    groups: "{{ apache_run_group }}"
    append: yes
    group: "{{ apache_admin_group }}"
  sudo: true

# Note this module requires the package python-passlib
- name: Apache | Create User password in Auth file
  htpasswd:
     path: "{{ apache_auth_htpasswd_file }}"
     name: "{{ item.username }}"
     password: "{{ item.password }}"
     owner: root
     group: "{{ apache_admin_user }}"
     mode: 0644
  no_log: True
  with_items:
    -  "{{ apache_auth_users }}"


# Todo write the authgroup file
# adding relevant users to groups
# see https://www.linode.com/docs/websites/authbased-access-control-with-apache
- name: Apache | Setup auth groups
  template:
    src: auth_htgroup.j2
    dest: "{{ apache_auth_htgroup_file }}"
    owner: root
    group: root
    mode: 0644
  sudo: true

# Apache user www-data is created on install of apache
# but may be apache on centos
- name: Apache | Add apache www-data user
  user: 
    name: "{{ apache_run_user }}"
    append: yes
    group: "{{ apache_run_group }}"
  sudo: true
